import Link from "next/link";
import { notFound } from "next/navigation";
import { courseBySlug } from "../../../../../../lib/platform/catalog";
import { demoLessonBody } from "../../../../../../lib/platform/lesson-content.server";
import { LessonTools } from "../../../../../../components/platform/lesson-tools";
import { Icon } from "../../../../../../components/platform/icon";
import styles from "../../../../../../components/platform/platform.module.css";
export default async function LessonPage({ params }: { params: Promise<{ slug: string; lessonId: string }> }) {
  const { slug, lessonId } = await params; const course = courseBySlug(slug); if (!course) notFound();
  const index = course.lessons.findIndex(item => item.id === lessonId); if (index < 0) notFound();
  const lesson = course.lessons[index]; const body = demoLessonBody(course, lessonId);
  if (!body) return <div className={styles.page}><Link className={styles.backLink} href={`/learn/courses/${course.slug}`}>‹ {course.title}</Link><div className={styles.empty}><Icon name="lock" width="36" height="36" /><h1>This lesson is not in the preview.</h1><p>Paid access is not connected. Saving a course or editing browser data cannot unlock this lesson.</p><Link className={styles.primaryButton} href={`/learn/courses/${course.slug}/lessons/${course.lessons[0].id}`}>Read the open sample</Link></div></div>;
  const next = course.lessons[index + 1]; const previous = course.lessons[index - 1];
  return <div className={styles.page}><Link className={styles.backLink} href={`/learn/courses/${course.slug}`}>‹ {course.title}</Link><div className={styles.readingLayout}><article className={styles.lessonArticle}><p className={styles.eyebrow}>LESSON {index + 1} OF {course.lessons.length} · {lesson.minutes} MIN READ</p><h1>{lesson.title}</h1><p className={styles.introduction}>{body.introduction}</p>{body.sections.map(section => <section key={section.title}><h2>{section.title}</h2><p>{section.body}</p></section>)}<section className={styles.exercise}><p className={styles.eyebrow}>MAKE IT YOURS</p><h2>A small experiment</h2><p>{body.exercise}</p><Link className={styles.textButton} href={`/learn/community?course=${course.id}`}>Bring it to the discussion <Icon name="arrow" /></Link></section><LessonTools key={lesson.id} courseId={course.id} lessonId={lesson.id} /><nav className={styles.lessonNavigation} aria-label="Lesson navigation">{previous ? <Link className={styles.secondaryButton} href={`/learn/courses/${course.slug}/lessons/${previous.id}`}>‹ Previous lesson</Link> : <span />}{next ? <Link className={styles.primaryButton} href={`/learn/courses/${course.slug}/lessons/${next.id}`}>Next lesson <Icon name="arrow" /></Link> : <Link className={styles.primaryButton} href="/learn/library">Back to my learning</Link>}</nav></article>
    <aside className={styles.lessonOutline}><p className={styles.eyebrow}>IN THIS COURSE</p><h2>{course.title}</h2><nav aria-label="Course lessons">{course.lessons.map((item, itemIndex) => <Link key={item.id} href={`/learn/courses/${course.slug}/lessons/${item.id}`} aria-current={item.id === lessonId ? "page" : undefined}><span>{String(itemIndex + 1).padStart(2, "0")}</span><div>{item.title}<small>{item.minutes} min read</small></div></Link>)}</nav><p>Reading progress and notes stay on this browser. Nothing here is a purchase receipt or enrollment.</p></aside></div></div>;
}
