"""Real creator/category journeys; independent of Apple reference acceptance."""
import re
from playwright.sync_api import expect
from browser_platform_contract import check_shell_contract


def check_rich_catalog(page, visit, out, passed, observations):
    page.set_viewport_size({"width": 1440, "height": 903})
    visit(page, "/learn")
    shelf = page.get_by_role("region", name="featured courses", exact=True)
    expect(shelf).to_be_visible()
    page.get_by_role("button", name="Next featured courses", exact=True).click()
    page.wait_for_function("document.querySelector('[aria-label=\"featured courses\"][role=region]').scrollLeft > 100")
    page.get_by_role("button", name="Previous featured courses", exact=True).click()
    page.wait_for_function("document.querySelector('[aria-label=\"featured courses\"][role=region]').scrollLeft < 2")
    shelf.focus(); shelf.press("ArrowRight")
    page.wait_for_function("document.querySelector('[aria-label=\"featured courses\"][role=region]').scrollLeft > 100")
    passed("Editorial shelves support Next, Previous and native keyboard navigation")
    page.get_by_role("link", name="See all creators", exact=False).click(); page.wait_for_load_state("networkidle", timeout=90000)
    expect(page.get_by_role("heading", name="Creators", exact=True)).to_be_visible(timeout=60000)
    page.get_by_role("link", name=re.compile("^Maya Chen Design")).click(); page.wait_for_load_state("networkidle", timeout=90000)
    expect(page.get_by_role("heading", name="Maya Chen", exact=True)).to_be_visible(timeout=60000)
    expect(page.get_by_role("navigation", name="Main navigation").get_by_role("link", name="Creators", exact=True)).to_have_attribute("aria-current", "page")
    before = page.evaluate("JSON.parse(localStorage.getItem('courses:learning-preview:v1'))")
    page.get_by_role("button", name="Follow Maya Chen", exact=True).click()
    page.reload(wait_until="networkidle")
    expect(page.get_by_role("button", name="Unfollow Maya Chen", exact=True)).to_have_attribute("aria-pressed", "true")
    after = page.evaluate("JSON.parse(localStorage.getItem('courses:learning-preview:v1'))")
    assert before["saved"] == after["saved"] and before["progress"] == after["progress"]
    page.get_by_role("link", name="Creators", exact=False).filter(has_text="‹ Creators").click(); page.wait_for_load_state("networkidle", timeout=90000)
    page.get_by_role("navigation", name="Creator collections").get_by_role("link", name="Following", exact=True).click(); page.wait_for_load_state("networkidle", timeout=90000)
    expect(page.get_by_role("heading", name="Maya Chen", exact=True)).to_be_visible(timeout=60000)
    expect(page.get_by_role("heading", name="Noah Reed", exact=True)).to_have_count(0)
    page.get_by_role("link", name=re.compile("^Maya Chen Design")).click(); page.wait_for_load_state("networkidle", timeout=90000)
    page.get_by_role("button", name="Unfollow Maya Chen", exact=True).click()
    expect(page.get_by_role("button", name="Follow Maya Chen", exact=True)).to_have_attribute("aria-pressed", "false")
    passed("Creator following persists, filters the directory and does not grant learning access")
    page.get_by_role("link", name="Explore courses", exact=True).click(); page.wait_for_load_state("networkidle", timeout=90000)
    expect(page.get_by_role("heading", name="Design with intention", level=1, exact=True)).to_be_visible(timeout=60000)
    page.get_by_role("link", name="Maya Chen ›", exact=True).click(); page.wait_for_load_state("networkidle", timeout=90000)
    page.get_by_role("link", name="Design ›", exact=True).click(); page.wait_for_load_state("networkidle", timeout=90000)
    expect(page.get_by_role("heading", name="Design", exact=True)).to_be_visible(timeout=60000)
    expect(page.get_by_role("navigation", name="Main navigation").get_by_role("link", name="Categories", exact=True)).to_have_attribute("aria-current", "page")
    page.get_by_role("link", name=re.compile("Start by noticing")).click(); page.wait_for_load_state("networkidle", timeout=90000)
    expect(page.get_by_role("heading", name="Start by noticing", exact=True)).to_be_visible(timeout=60000)
    passed("Creator to course to creator to category to lesson works through real links")
    page.get_by_role("navigation", name="Main navigation").get_by_role("link", name="Search", exact=True).click(); page.wait_for_load_state("networkidle", timeout=90000)
    expect(page.get_by_role("heading", name="Search", level=1, exact=True)).to_be_visible(timeout=60000)
    page.get_by_label("Search courses", exact=True).fill("Maya Chen")
    page.get_by_role("button", name="Search", exact=True).click()
    expect(page.get_by_role("heading", name="Maya Chen", exact=True)).to_be_visible(timeout=60000)
    expect(page.get_by_role("heading", name="Design with intention", exact=True)).to_be_visible(timeout=60000)
    expect(page.get_by_role("heading", name="Build for the web", exact=True)).to_have_count(0)
    page.go_back(wait_until="networkidle")
    expect(page.get_by_role("heading", name="Browse categories", exact=True)).to_be_visible(timeout=60000)
    passed("Search finds creators and their courses; browser Back restores browsing")
    for route in ["/learn/creators/not-a-person", "/learn/categories/not-a-category"]:
        visit(page, route)
        expect(page.get_by_role("heading", name=re.compile("That chapter"))).to_be_visible(timeout=60000)
    passed("Unknown creator and category URLs show recoverable not-found states")
    for width in [320, 390, 768, 1024, 1280, 1440]:
        page.set_viewport_size({"width": width, "height": 903 if width > 760 else 844})
        for route, name in [("/learn/creators", "creators"), ("/learn/creators/maya-chen", "creator"), ("/learn/categories", "categories"), ("/learn/categories/design", "category")]:
            visit(page, route); expect(page.locator("h1")).to_be_visible()
            check_shell_contract(page, width, observations)
            assert not page.locator("main").evaluate("e => e.scrollWidth > e.clientWidth + 1"), (width, route)
            page.screenshot(path=str(out / f"{name}-{width}.png"))
        if width <= 760:
            nav = page.get_by_role("navigation", name="Main navigation")
            nav.get_by_role("link", name="Saved", exact=True).focus()
            nav.get_by_role("link", name="Saved", exact=True).press("Enter")
            expect(page.get_by_role("heading", name="Saved", exact=True)).to_be_visible(timeout=60000)
        passed(f"Creator and category surfaces preserve shell and containment at {width}px")
    page.set_viewport_size({"width": 1440, "height": 903})
    visit(page, "/learn")
