"""Real-control shared search and collection regressions; not Apple acceptance."""
import re
from playwright.sync_api import expect

KEY = "courses:learning-preview:v1"

def check_search_and_collections(page, visit, out, passed):
    page.set_viewport_size({"width":1440,"height":903})
    visit(page, "/learn/creators/maya-chen")
    search = page.get_by_role("combobox", name="Search courses", exact=True)
    page.keyboard.press("Control+k"); expect(search).to_be_focused()
    search.fill("Noah")
    expect(page.get_by_role("option",name=re.compile("Noah Reed"))).to_be_visible()
    search.press("Escape"); expect(search).to_have_attribute("aria-expanded","false")
    expect(search).to_have_value("Noah")
    search.press("ArrowDown"); search.press("Enter")
    expect(page.get_by_role("heading",name="Noah Reed",level=1,exact=True)).to_be_visible(timeout=60000)
    passed("Persistent search supports shortcut, suggestions, Escape and keyboard selection from creator pages")
    search.fill("design"); page.get_by_role("button",name="Search",exact=True).click()
    expect(page.get_by_role("heading",name="Search",level=1,exact=True)).to_be_visible(timeout=60000)
    kinds=page.get_by_role("navigation",name="Result type")
    kinds.get_by_role("link",name=re.compile("^Lessons ")).click()
    expect(kinds.get_by_role("link",name=re.compile("^Lessons "))).to_have_attribute("aria-current","page")
    expect(page.get_by_role("heading",name="Lessons",exact=True)).to_be_visible()
    expect(page.get_by_role("heading",name="Design with intention",exact=True)).to_have_count(0)
    kinds.get_by_role("link",name=re.compile("^Courses ")).click()
    expect(page.get_by_role("heading",name="Design with intention",exact=True)).to_be_visible()
    page.go_back(wait_until="networkidle")
    expect(kinds.get_by_role("link",name=re.compile("^Lessons "))).to_have_attribute("aria-current","page")
    expect(search).to_have_value("design")
    passed("Result types and browser Back preserve the query and filter real entities")
    search.fill("Noah"); page.get_by_role("button",name="Search",exact=True).click()
    expect(page.get_by_role("heading",name="Noah Reed",exact=True)).to_be_visible()
    page.get_by_role("navigation",name="Search scope").get_by_role("link",name="Your Library",exact=True).click()
    expect(page.get_by_role("heading",name="No results in this view.",exact=True)).to_be_visible()
    page.get_by_role("navigation",name="Search scope").get_by_role("link",name="All Courses",exact=True).click()
    expect(page.get_by_role("heading",name="Noah Reed",exact=True)).to_be_visible()
    passed("Your Library search limits results to saved and started courses without granting access")
    visit(page,"/learn/search")
    recent=page.get_by_role("region",name="Recent searches")
    expect(recent.get_by_role("link",name="Noah",exact=True)).to_be_visible()
    before=page.evaluate("key=>JSON.parse(localStorage.getItem(key))",KEY)
    recent.get_by_role("button",name="Remove recent search Noah",exact=True).click()
    page.reload(wait_until="networkidle")
    expect(page.get_by_role("link",name="Noah",exact=True)).to_have_count(0)
    page.get_by_role("button",name="Clear recent searches",exact=True).click()
    after=page.evaluate("key=>JSON.parse(localStorage.getItem(key))",KEY)
    assert after["recentSearches"]==[] and after["notes"]==before["notes"] and after["saved"]==before["saved"]
    passed("Recent searches survive reload, support removal and clear without touching learning data")
    visit(page,"/learn/courses")
    page.get_by_label("Availability",exact=True).select_option("free")
    page.get_by_label("Sort by",exact=True).select_option("duration")
    page.get_by_role("button",name="Apply filters",exact=True).click()
    expect(page.locator('[data-catalog-grid] > div')).to_have_count(2)
    page.get_by_role("link",name="List view",exact=True).click()
    listing=page.get_by_role("list",name="Courses list")
    expect(listing.get_by_role("listitem")).to_have_count(2)
    expect(listing.get_by_role("listitem").first).to_contain_text("Make your ideas clear")
    page.reload(wait_until="networkidle")
    expect(page.get_by_role("link",name="List view",exact=True)).to_have_attribute("aria-current","page")
    expect(page.get_by_label("Availability",exact=True)).to_have_value("free")
    page.screenshot(path=str(out/"collection-list-filtered-1440.png"))
    listing.get_by_role("button",name="Save Make your ideas clear",exact=True).click()
    expect(listing.get_by_role("button",name="Unsave Make your ideas clear",exact=True)).to_have_attribute("aria-pressed","true")
    page.get_by_role("navigation",name="Main navigation").get_by_role("link",name="Saved",exact=True).click()
    expect(page.get_by_role("heading",name="Saved",level=1,exact=True)).to_be_visible(timeout=60000)
    expect(page.get_by_role("heading",name="Make your ideas clear",exact=True)).to_be_visible()
    page.get_by_label("Filter courses",exact=True).fill("no-such-course")
    page.get_by_role("button",name="Apply filters",exact=True).click()
    expect(page.get_by_role("heading",name="No courses match these filters.",exact=True)).to_be_visible()
    page.get_by_role("link",name="Clear filters",exact=True).click()
    expect(page.get_by_role("heading",name="Make your ideas clear",exact=True)).to_be_visible()
    page.get_by_role("navigation",name="Main navigation").get_by_role("link",name="My learning",exact=True).click()
    expect(page.get_by_role("heading",name="My learning",level=1,exact=True)).to_be_visible(timeout=60000)
    page.get_by_role("link",name="List view",exact=True).click()
    expect(page.get_by_role("list",name="Courses list").get_by_text(re.compile("complete in this browser"))).to_be_visible()
    passed("Collections filter, sort, switch grid/list, preserve progress, save, reload and recover from empty results")
    visit(page,"/learn/courses/design-with-intention/lessons/design-observe")
    note=page.get_by_label("Your lesson notes",exact=False)
    note.fill("Draft must survive global search navigation.")
    page.keyboard.press("Control+k"); search.fill("Writing")
    page.once("dialog",lambda dialog:dialog.dismiss())
    page.get_by_role("button",name="Search",exact=True).click()
    expect(note).to_have_value("Draft must survive global search navigation.")
    assert "/lessons/design-observe" in page.url
    page.get_by_role("button",name="Save note",exact=True).click()
    expect(page.get_by_text("Note saved in this browser.",exact=True)).to_be_visible()
    page.get_by_role("button",name="Search",exact=True).click()
    expect(page.get_by_role("heading",name="Search",level=1,exact=True)).to_be_visible(timeout=60000)
    passed("Global search respects the unsaved lesson-note navigation guard")
    visit(page,"/learn/search?q=design")
    page.screenshot(path=str(out/"search-results-1440.png"))
    visit(page,"/learn/courses")
    page.keyboard.press("Control+k"); search.fill("design")
    expect(page.get_by_role("listbox",name="Search suggestions")).to_be_visible()
    page.screenshot(path=str(out/"search-suggestions-1440.png"))
    search.press("Escape")
    for width in [320,390,768,1024,1280,1440]:
        page.set_viewport_size({"width":width,"height":844 if width<761 else 903})
        for route,name in [("/learn/search?q=design","search"),("/learn/courses?view=list","list")]:
            visit(page,route)
            expect(search).to_be_visible()
            assert not page.locator("main").evaluate("e=>e.scrollWidth>e.clientWidth+1"),(width,route)
            page.screenshot(path=str(out/f"{name}-ux-{width}.png"))
    passed("Search results and list collections contain content at all six widths")
    page.set_viewport_size({"width":1440,"height":903}); visit(page,"/learn")
