"use client";

import { useMemo, useState, type ReactNode } from "react";
import { albumArt, albumTitle, albumTracks, allTracks, artistHero, categories, crop, emotionalArt, favouriteArt, features, formatTime, libraryCovers, libraryTracks, radioStations, recentlyPlayed, sourArt, topPicks, viralTracks, type Card, type Track } from "../lib/music-catalog";
import { useMusic } from "./music-context";
import { Art, EmptyState, Footer, Glyph, IconButton, Rail, Section } from "./music-primitives";

export function SongRow({ track, showTime = false, trailing }: { track: Track; showTime?: boolean; trailing?: ReactNode }) {
  const m = useMusic();
  return <div className="song-row" data-active={m.activeId === track.id && m.playing}>
    <button type="button" className="song-art-button" aria-label={`Play ${track.title}`} onClick={() => m.play(track)}><Art art={track.art} label={track.album} /><span className="art-play"><Glyph name={m.activeId === track.id && m.playing ? "pause" : "play"} /></span></button>
    <div className="song-copy"><button className="song-title" type="button" onClick={() => m.play(track)}>{track.title}{track.explicit && <span className="explicit" aria-label="Explicit">E</span>}</button><button className="song-artist" type="button" onClick={() => m.go(`artist:${track.artist}`)}>{track.artist}</button></div>
    {showTime && <span className="duration">{track.duration ? formatTime(track.duration) : "—"}</span>}
    {trailing ?? <IconButton icon="more" label={`More actions for ${track.title}`} onClick={(event) => m.openMenu("track", event, track.id)} />}
  </div>;
}
export function CardTile({ card, poster = false }: { card: Card; poster?: boolean }) {
  const { go } = useMusic();
  const destination = card.destination.includes(":") || !["album", "artist"].includes(card.destination) ? card.destination : `${card.destination}:${card.id}`;
  return <article className={`media-card ${poster ? "poster-card" : ""}`}><button className="card-art-button" type="button" onClick={() => go(destination)} aria-label={card.title}><Art art={card.art} label={card.title} /><span className="card-play"><Glyph name="play" size={22} /></span></button>{!poster && <><button type="button" className="card-title" onClick={() => go(destination)}>{card.title}</button>{card.subtitle && <p>{card.subtitle}</p>}</>}</article>;
}
function CardRail({ cards, label, poster = false }: { cards: Card[]; label: string; poster?: boolean }) { return <Rail label={label} className={poster ? "poster-rail" : "square-rail"}>{cards.map(card => <CardTile key={card.id} card={card} poster={poster} />)}</Rail>; }

export function NewView() {
  const m = useMusic();
  const ordered = m.scene.hero === "superbloom" ? [...features.slice(2,4), ...features.slice(0,2), ...features.slice(4)] : m.scene.hero === "alpha" ? [...features.slice(4), ...features.slice(0,4)] : features;
  const essentials = ["Olivia Rodrigo Essentials", "Ariana Grande Essentials", "Set List", "Drake Essentials", "The Weeknd Essentials"].map((title, i): Card => ({ id: `essential-${i}`, title, subtitle: "Apple Music", destination: "artist", art: crop("8b03c9d0", 286 + i * 227, 61, 207, 207) }));
  const charts = ["Top 100: Singapore", "Top 100: Global", "Top 100: Taiwan", "Top 100: USA", "Top 100: United Kingdom"].map((title, i): Card => ({ id: `chart-${i}`, title, subtitle: "Apple Music", destination: `category:${title}`, art: crop("8b03c9d0", 286 + i * 227, 388, 207, 207) }));
  const coming = ["The Red Tape", "Last Dance", "Good Grief", "WILDCHILD", "Heaven"].map((title, i): Card => ({ id: `coming-${i}`, title, subtitle: "Coming Soon", destination: "album", art: crop("706de500", 286 + i * 227, 150, 207, 207) }));
  return <div className="page-content new-page"><h1>{m.library.locale === "zh" ? "新发现" : "New"}</h1>
    <Rail label="Featured music" className="feature-rail">{ordered.map(card => <article className="feature-card" key={card.id}><div className="feature-caption"><small>{card.kicker}</small><button type="button" onClick={() => m.go(card.destination === "album" ? `album:${card.id}` : `category:${card.title}`)}>{card.title}</button><span>{card.subtitle || "Apple Music"}</span></div><button className="card-art-button" type="button" aria-label={`Open ${card.title}`} onClick={() => m.go(card.destination === "album" ? `album:${card.id}` : `category:${card.title}`)}><Art art={card.art} label={card.title} /></button></article>)}</Rail>
    <Section title="☆ Favourite These Viral Hits" onMore={() => m.go("chart")}><Rail label="Viral songs" className="song-rail"><div className="viral-grid">{viralTracks.filter(track => !m.library.restrictions || !track.explicit).map(track => <SongRow key={track.id} track={track} />)}</div></Rail></Section>
    <Section title="New This Week" onMore={() => m.go("category:New This Week")}><CardRail cards={libraryCovers.filter((_,i)=>[9,4,1,5,7].includes(i))} label="New releases" /></Section>
    <Section title="Essential Listening" id="essentials" onMore={() => m.go("category:Essentials")}><CardRail cards={essentials} label="Essentials" /></Section>
    <Section title="Daily Top 100" id="daily-top" onMore={() => m.go("category:Daily Top 100")}><CardRail cards={charts} label="Daily Top 100" /></Section>
    <Section title="Coming Soon" id="coming-soon" onMore={() => m.go("category:Coming Soon")}><CardRail cards={coming} label="Coming soon" /></Section>
    <Section title="More to Explore"><div className="explore-grid">{["Concerts", "Moods and Activities", "Spatial Audio", "Browse by Genre", "Worldwide", "Decades", "Charts"].map(title => <button type="button" key={title} onClick={() => m.go(title === "Concerts" ? "concerts" : `category:${title}`)}>{title}<Glyph name="chevron" size={14} /></button>)}</div></Section><Footer />
  </div>;
}
export function HomeView() {
  const m = useMusic();
  if (m.scene.guest) return <div className="membership-home"><div className="brand"><Glyph name="apple" />Music</div><h1>Discover new music<br />every day.</h1><div className="membership-note"><Glyph name="music" size={270} /></div><p>Get playlists and albums inspired by the artists and genres you’re streaming.</p><button type="button" className="pill white" onClick={() => m.patch({ overlay: "signin" })}>Try It Free</button></div>;
  return <div className="page-content home-page"><h1>{m.library.locale === "zh" ? "主页" : "Home"}</h1><Section title="Top Picks for You"><CardRail cards={m.scene.hero === "alpha" ? [...topPicks.slice(3), ...topPicks.slice(0,3)] : topPicks} label="Top picks" poster /></Section><Section title="Recently Played" onMore={() => m.go("library")}><CardRail cards={recentlyPlayed} label="Recently played" /></Section><Section title="Pop" onMore={() => m.go("category:Pop")}><CardRail cards={libraryCovers.filter((_,i)=>i>3&&i!==8)} label="Pop" /></Section><Section title="Add to Your Library" id="add-library" onMore={() => m.go("library")}><CardRail cards={[...libraryCovers].reverse()} label="Albums for your library" /></Section><Section title="Concerts"><div className="concert-callout"><Glyph name="ticket" size={32} /><div><strong>Find Concerts Nearby</strong><p>Upcoming shows of interest to you.</p></div><button type="button" onClick={() => m.go("concerts")}>Set Location</button></div></Section><Footer /></div>;
}

export function SearchView() {
  const m = useMusic(); const [focused, setFocused] = useState(Boolean(m.scene.filled)); const [recent, setRecent] = useState(["Ariana Grande", "Billie Eilish"]);
  const query = m.scene.query ?? ""; const scope = m.scene.scope ?? "catalog";
  const results = useMemo(() => (scope === "library" ? allTracks.filter(track=>m.library.songs.includes(track.id)) : allTracks).filter(track => (!m.library.restrictions || !track.explicit) && `${track.title} ${track.artist} ${track.album}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [query, scope, m.library.songs, m.library.restrictions]);
  const artists = [...new Set(results.map(track=>track.artist))];
  const submit = () => { setFocused(false); m.patch({ query: query.trim(), empty: false, filled: false }); window.history.replaceState({}, "", `/?view=search&q=${encodeURIComponent(query.trim())}&scope=${scope}`); };
  return <div className="page-content search-page"><div className="search-toolbar"><form className="search-field" role="search" onSubmit={event=>{event.preventDefault();submit();}}><Glyph name="search" size={15} /><input aria-label="Search Apple Music" value={query} placeholder="Search" autoComplete="off" onFocus={()=>setFocused(true)} onBlur={()=>setFocused(false)} onChange={event=>m.patch({ query: event.target.value, empty: false })} />{query && <IconButton icon="close" label="Clear search" onClick={()=>m.patch({ query: "" })} />}</form><div className="segmented" aria-label="Search scope"><button type="button" aria-pressed={scope === "catalog"} onClick={()=>m.patch({ scope: "catalog" })}>Apple Music</button><button type="button" aria-pressed={scope === "library"} onClick={()=>m.patch({ scope: "library", empty: !query })}>Your Library</button></div></div>
    {focused && query && <div className="search-suggestions" role="listbox" aria-label="Search suggestions">{artists.slice(0,5).map(artist=><button key={artist} role="option" aria-selected={false} type="button" onMouseDown={event=>event.preventDefault()} onClick={()=>{m.patch({ query: artist, filled: false });setFocused(false);}}><Glyph name="search" size={15} />{artist}</button>)}<button type="button" onMouseDown={event=>event.preventDefault()} onClick={submit}>Search for “{query}”</button></div>}
    {query && !focused ? <>{results.length ? <><Section title={scope === "library" ? "Songs" : "Top Results"}><div className="search-result-grid">{results.slice(0,6).map(track=><SongRow key={track.id} track={track} />)}</div></Section><Section title="Artists"><div className="artist-bubbles">{artists.slice(0,8).map((artist,i)=><button type="button" key={artist} onClick={()=>m.go(`artist:${artist}`)}><Art art={results.find(track=>track.artist===artist)?.art ?? albumArt} label={artist} /><span>{artist}</span></button>)}</div></Section>{scope !== "library" && <Section title="Albums"><CardRail cards={libraryCovers.filter(card => card.subtitle?.toLowerCase().includes(query.toLowerCase()) || card.title.toLowerCase().includes(query.toLowerCase())).slice(0,8)} label="Search albums" /></Section>}</> : <EmptyState icon="search" title="No results" description={`No saved catalog results for “${query}”. Try a song, album, or artist name.`} />}</> : scope === "library" ? <EmptyState icon="search" description="Search in Library" /> : <><Section title="Recently Searched"><button type="button" className="clear-recents" onClick={()=>setRecent([])}>Clear</button><div className="recent-searches">{recent.map((artist,i)=><button type="button" key={artist} onClick={()=>{m.patch({ query: artist, filled: false });setFocused(false);}}><Art art={crop("035569a0", i === 0 ? 300 : 584, 117, 39, 39)} label={artist} /><span>{artist}<small>Artist</small></span></button>)}</div></Section><Section title="Browse Categories"><div className="category-grid">{categories.map((card,i)=><div key={card.id} id={i===12?"more-categories":undefined}><CardTile card={card} poster /></div>)}</div></Section></>}
    <Footer />
  </div>;
}

export function TrackTable({ tracks, album = false, heading = true }: { tracks: Track[]; album?: boolean; heading?: boolean }) {
  const m = useMusic();
  return <div className={`track-table ${album ? "album-table" : ""}`} role="table" aria-label={album ? "Album songs" : "Songs"}>{heading && !album && <div className="track-table-head" role="row"><span role="columnheader">Name</span><span role="columnheader">Artist</span><span role="columnheader">Album</span><span role="columnheader">Time</span></div>}{tracks.map((track, index)=><div role="row" key={track.id} className="track-table-row" data-selected={album && (m.activeId === track.id || (!m.activeId && track.id === "album-2"))} data-unavailable={track.unavailable || undefined}>
    <div className="track-name" role="cell">{album ? <span className="track-number">{index+1}</span> : <button type="button" className="favourite-marker" aria-label={`${m.library.favourites.includes(track.id)?"Unfavourite":"Favourite"} ${track.title}`} aria-pressed={m.library.favourites.includes(track.id)} onClick={()=>m.favourite(track.id)}>{m.library.favourites.includes(track.id) && <Glyph name="star" size={10} />}</button>}{!album && <button className="table-art" type="button" onClick={()=>m.play(track)} aria-label={`Play ${track.title}`}><Art art={track.art} label={track.album} /></button>}<button type="button" className="table-song-title" onClick={()=>m.play(track)} disabled={track.unavailable}>{track.title}{track.explicit && <span className="explicit">E</span>}</button></div>
    {!album && <><button type="button" role="cell" className="table-text-link" onClick={()=>m.go(`artist:${track.artist}`)}>{track.artist}</button><button type="button" role="cell" className="table-text-link" onClick={()=>m.go(track.album === albumTitle ? "album" : `album:${track.album}`)}>{track.album}</button></>}
    <span role="cell" className="track-time">{track.duration ? formatTime(track.duration) : ""}</span><IconButton icon="more" label={`More actions for ${track.title}`} onClick={event=>m.openMenu("track",event,track.id)} />
  </div>)}</div>;
}
export function LibraryView() {
  const m = useMusic(); const page = m.scene.page;
  const title = ({ library: "Recently Added", artists: "Artists", albums: "Albums", songs: "Songs", videos: "Music Videos", "made-for-you": "Made for You", playlists: "All Playlists" } as Record<string,string>)[page] ?? "Library";
  const artist = m.scene.selectedArtist ?? "Ariana Grande";
  let tracks = allTracks.filter(track=>m.library.songs.includes(track.id) && (!m.library.restrictions || !track.explicit));
  tracks = tracks.sort((a,b)=>a.title.localeCompare(b.title)); if (m.scene.sort === "descending") tracks.reverse();
  const albums = [libraryCovers[7]!, libraryCovers[4]!, libraryCovers[5]!, libraryCovers[1]!, libraryCovers[6]!, libraryCovers[9]!];
  const madeForYou = ["Chill", "Get Up!", "Heavy Rotation", "New Music", "Your Essentials"].map((title,i):Card=>({ id:`mix-${i}`, title, subtitle:"Apple Music", destination:`category:${title}`, art:crop("e379e3fe",286+i*227,65,207,207) }));
  const playlists: Card[] = [...m.library.playlists.map(p=>({ id:p.id,title:p.name,subtitle:"",art:emotionalArt,destination:`playlist:${p.id}` })),{id:"favourite-songs",title:"Favourite Songs",subtitle:"Apple Music",art:favouriteArt,destination:"favourites"}];
  if (page === "library" && !m.library.songs.length) return <div className="library-page"><EmptyState title="Add music to your library." description="Browse millions of songs and save your favourites here." action="Browse Apple Music" onAction={()=>m.go("new")} /><Footer /></div>;
  if (page === "made-for-you" && m.scene.empty) return <div className="library-page"><EmptyState icon="person" description="Personal mixes that you add will appear here." /><Footer /></div>;
  return <div className={`library-page ${page === "artists" ? "with-artist-list" : ""}`}><div className="library-topbar"><h1>{title}</h1><IconButton icon="sort" label={`Sort ${title}`} onClick={event=>m.openMenu("sort",event)} /></div>{page === "songs" ? <TrackTable tracks={tracks} /> : page === "artists" ? <><aside className="library-artist-list" aria-label="Library artists">{["Ariana Grande","Billie Eilish","Olivia Dean","Olivia Rodrigo","Taylor Swift"].map(name=><button type="button" key={name} data-active={name===artist} onClick={()=>m.patch({ selectedArtist:name })}><Art art={libraryTracks.find(t=>t.artist===name)?.art ?? albumArt} label={name}/>{name}</button>)}</aside><div className="library-artist-content"><h2><button type="button" onClick={()=>m.go(`artist:${artist}`)}>{artist} <Glyph name="chevron" size={13}/></button></h2><div className="library-grid">{albums.filter(card=>card.subtitle===artist).map(card=><CardTile key={card.id} card={card}/>)}</div></div></> : <div className="library-grid">{(page === "playlists" ? playlists : page === "made-for-you" ? madeForYou : page === "albums" ? albums : page === "videos" ? libraryCovers.filter((_,i)=>[0,2,3].includes(i)) : [...libraryCovers,...playlists.slice(-1)]).map(card=><CardTile key={card.id} card={card}/>)}</div>}<Footer /></div>;
}

export function AlbumView() {
  const m = useMusic(); const isPlaylist = m.scene.page === "playlist"; const favourites = m.scene.page === "favourites";
  const selectedPlaylist = m.library.playlists.find(p=>p.id === (m.scene.category ?? "emotional")) ?? m.library.playlists[0];
  const other = m.scene.category && !isPlaylist ? [...libraryCovers,...features].find(card=>card.id===m.scene.category || card.title===m.scene.category) : null;
  const title = favourites ? "Favourite Songs" : isPlaylist ? selectedPlaylist?.name ?? "Playlist" : other?.title ?? albumTitle;
  const artist = favourites ? "Apple Music" : isPlaylist ? "Alex Smith" : other?.subtitle ?? "Olivia Rodrigo";
  const art = favourites ? favouriteArt : isPlaylist ? emotionalArt : other?.art ?? albumArt;
  const tracks = favourites ? allTracks.filter(track=>m.library.favourites.includes(track.id)) : isPlaylist ? (selectedPlaylist?.tracks ?? []).flatMap(id=>{const track=allTracks.find(t=>t.id===id);return track?[track]:[];}) : other && other.title!==albumTitle ? [] : albumTracks;
  return <div className="page-content album-page"><div className="detail-tools"><IconButton icon="share" label={`Share ${title}`} onClick={event=>m.openMenu("share",event)}/><IconButton icon="more" label={`More actions for ${title}`} onClick={event=>m.openMenu("album",event)}/></div><header className="album-header"><Art art={art} label={title}/><div className="album-information"><h1>{title}{!isPlaylist&&!favourites&&!other&&<span className="explicit">E</span>}</h1><button type="button" className="album-artist" onClick={()=>m.go(`artist:${artist}`)}>{artist}</button><p className="album-meta">{isPlaylist ? "" : favourites ? "" : "Pop · 2026"}</p>{!isPlaylist&&!favourites&&<div className="album-summary"><strong>A pop savant raises her game and her standards on her third album.</strong><p>Read the editorial notes for this album. <button type="button" onClick={()=>m.patch({ overlay:"article" })}>MORE</button></p></div>}<div className="album-actions"><IconButton icon="shuffle" label={`Shuffle ${title}`} className="round-button" onClick={()=>{m.setShuffle(!m.shuffle);if(tracks[0])m.play(tracks[0]);}}/><button type="button" className="pill dark" disabled={!tracks.length} onClick={()=>tracks[0]&&m.play(tracks[0])}><Glyph name="play" size={16}/>Play</button><IconButton icon={m.library.songs.includes("album-1")||isPlaylist?"check":"plus"} label="Add album to library" className="round-button" onClick={()=>m.setLibrary(data=>({...data,songs:[...new Set([...data.songs,...tracks.map(t=>t.id)])]}))}/></div></div></header>
    {tracks.length ? <TrackTable tracks={tracks} album={!isPlaylist&&!favourites}/> : <p className="catalog-notice">The saved reference includes this artwork, but not this release’s track listing. No unrelated album has been substituted.</p>}
    <p className="album-footnote">{tracks.length} songs{tracks.length>0?`, ${Math.round(tracks.reduce((n,t)=>n+t.duration,0)/60)} minutes`:""}</p>
    {isPlaylist ? <Section title="Suggested Songs" className="suggested-songs"><div className="suggestion-grid">{allTracks.filter(track=>!tracks.some(t=>t.id===track.id)).slice(0,6).map(track=><SongRow key={track.id} track={track} trailing={<IconButton icon="plus" label={`Add ${track.title} to ${title}`} onClick={()=>m.setLibrary(data=>({...data,playlists:data.playlists.map(p=>p.id===selectedPlaylist?.id?{...p,tracks:[...new Set([...p.tracks,track.id])]}:p)}))}/>}/>)}</div></Section> : !favourites && <><Section title="Other Versions" id="other-versions"><div className="small-card-row"><CardTile card={{id:"album-original",title:albumTitle,subtitle:"Olivia Rodrigo",art:albumArt,destination:"album"}}/></div></Section><Section title="Music Videos" id="music-videos" onMore={()=>m.go("videos")}><CardRail cards={libraryCovers.filter((_,i)=>[0,2,3].includes(i))} label="Music videos"/></Section><Section title="More to Hear"><CardRail cards={topPicks} label="More to hear"/></Section></>}
    <Footer /></div>;
}

export function ArtistView() {
  const m = useMusic(); const name = m.scene.category && !m.scene.category.startsWith("essential-") ? m.scene.category : "Olivia Rodrigo"; const original = name === "Olivia Rodrigo" || name === "livies";
  return <div className="artist-page"><header className={`artist-hero ${!original?"artist-hero-compact":""}`}>{original ? <Art art={artistHero} label="Olivia Rodrigo artist artwork"/> : <Art art={allTracks.find(track=>track.artist===name)?.art??albumArt} label={name}/>}<div className="artist-hero-actions"><button type="button" className="round-button primary" aria-label={`Play ${name}`} onClick={()=>m.play(allTracks.find(track=>track.artist===name)??albumTracks[0]!)}><Glyph name="play" size={18}/></button><h1>{original?"Olivia Rodrigo":name}</h1><IconButton icon="star" label={`Favourite ${name}`} onClick={()=>{m.favourite("album-2");m.notify("Artist preference updated in this local preview.");}}/></div></header><div className="page-content"><div className="artist-top-grid"><Section title="Latest Release"><div className="latest-release"><button type="button" onClick={()=>m.go("album")}><Art art={albumArt} label={albumTitle}/></button><div><small>12 JUNE 2026</small><button type="button" onClick={()=>m.go("album")}>{albumTitle}</button><small>13 songs</small><button type="button" className="text-accent" onClick={()=>m.play(albumTracks[0]!)}><Glyph name="play" size={12}/>Play</button></div></div></Section><Section title="Top Songs" onMore={()=>m.go("chart")}><div className="artist-songs">{albumTracks.slice(0,6).map(track=><SongRow key={track.id} track={track}/>)}</div></Section></div><Section title="Essential Albums" id="essential-albums"><div className="small-card-row"><CardTile card={{id:"sour",title:"SOUR (Video Version)",subtitle:"Olivia Rodrigo",art:sourArt,destination:"album"}}/></div></Section><Section title="Albums" onMore={()=>m.go("albums")}><CardRail cards={libraryCovers.filter(card=>card.subtitle==="Olivia Rodrigo")} label="Artist albums"/></Section><Section title="Music Videos" id="music-videos" onMore={()=>m.go("videos")}><CardRail cards={libraryCovers.filter((_,i)=>[0,2,3].includes(i))} label="Artist music videos"/></Section><Section title="Nearby Concerts" id="nearby-concerts" onMore={()=>m.go("nearby")}><div className="concert-list">{[12,13,30,26,27,30,1,4,5,8].map((day,i)=><button type="button" key={`${day}-${i}`} onClick={()=>m.go("concert")}><span><small>{i<2?"OCT":"SEP"}</small>{day}</span><div><strong>{i%2?"Chicago":"Boston"}</strong><p>Olivia Rodrigo · 7:00 PM</p></div><Glyph name="chevron" size={14}/></button>)}</div></Section><Section title="About Olivia Rodrigo" id="about-artist"><div className="artist-about"><p>Explore Olivia Rodrigo’s latest releases, albums, music videos, and concert dates.</p><dl><dt>Born</dt><dd>February 20, 2003</dd><dt>Genre</dt><dd>Pop</dd></dl></div></Section><Footer /></div></div>;
}

export function RadioView() {
  const m = useMusic();
  const episodes = ["JAY-Z, Reasonable Doubt: Essentials","JAY-Z","JAY-Z Day","JAY-Z Day","Ride At Dawn","Rap Life’s Biggest Records"];
  return <div className="page-content radio-page"><h1>Radio</h1><Section title="Live Radio"><p className="section-description">Tap a station to hear non-stop music and more.</p><Rail label="Live radio" className="station-rail">{radioStations.map(station=><article className="station-card" key={station.id}><button type="button" className="card-art-button" onClick={()=>m.go(station.destination)} aria-label={`Listen to ${station.title}`}><Art art={station.art} label={station.title}/><span className="card-play"><Glyph name="play"/></span></button><IconButton icon="more" label={`${station.title} options`} onClick={event=>m.openMenu("station",event)}/></article>)}</Rail></Section><Section title="Latest Episodes" onMore={()=>m.go("schedule")}><div className="episode-grid">{episodes.map((title,i)=><article className="episode" key={`${title}-${i}`}><button type="button" onClick={()=>m.go("station:1")}><Art art={crop("4cb8f3aa",286+Math.floor(i/2)*379,392+(i%2)*115,92,92)} label={title}/></button><div><small>{["ESSENTIALS RADIO","THE EBRO SHOW","THE DOTTY SHOW","THE MATT WILKINSON SHOW","COLOR ME COUNTRY RADIO","RAP LIFE RADIO"][i]}</small><button type="button" onClick={()=>m.go("station:1")}>{title}</button><p>Listen on Apple Music Radio.</p></div><IconButton icon="more" label={`Options for ${title}`} onClick={event=>m.openMenu("station",event)}/></article>)}</div></Section><Section title="Artists Take Over" onMore={()=>m.go("category:Radio takeovers")}><CardRail cards={["Tyler White","Fancy Hagood","SIENNA SPIRO","The Cowgays","Shaboozey"].map((title,i)=>({id:`takeover-${i}`,title,art:crop("4cb8f3aa",286+i*227,675,207,207),destination:"station:1"}))} label="Artists take over"/></Section><Section title="Find Your Station" id="radio-stations"><CardRail cards={recentlyPlayed} label="Stations"/></Section><Footer /></div>;
}
export function ChartView() { const m=useMusic(); return <div className="page-content chart-page"><h1>☆ Favourite These Viral Hits</h1><TrackTable tracks={viralTracks.filter(track=>!m.library.restrictions||!track.explicit)}/><Footer/></div>; }
export function CategoryView() { const m=useMusic(); return <div className="page-content"><h1>{m.scene.category??"Browse"}</h1><Section title="Explore"><div className="library-grid">{[...libraryCovers,...recentlyPlayed].map(card=><CardTile key={card.id} card={card}/>)}</div></Section><Footer/></div>; }
export function ScheduleView() { const m=useMusic(); return <div className="page-content"><h1>Apple Music Hits Schedule</h1><div className="schedule-grid">{Array.from({length:13},(_,i)=><button type="button" key={i} onClick={()=>m.go("station:1")}><Art art={radioStations[1]!.art} label="Apple Music Hits"/><div><small>{String(i+8).padStart(2,"0")}:00–{String(i+9).padStart(2,"0")}:00</small><strong>Apple Music Hits</strong><p>Music and more with Apple Music Radio.</p></div></button>)}</div><Footer/></div>; }
