// Isolated layout-study fixtures. No real availability, booking, or live broadcast.
export const sampleEvents = [
  {
    id: "a-better-brief",
    title: "A better brief, together",
    creator: "Maya Chen",
    courseId: "useful-ai",
    location: "Online",
    month: "Sep",
    day: "18",
    date: "Friday, 18 September 2026",
    time: "18:00 UTC",
    subject: "ai-coding",
    image: "code.webp",
    description:
      "An example workshop about asking useful questions and reviewing a first draft.",
  },
  {
    id: "first-ideas",
    title: "From a question to an idea",
    creator: "Nora Ellis",
    courseId: "business",
    location: "London",
    month: "Sep",
    day: "24",
    date: "Thursday, 24 September 2026",
    time: "17:00 UTC",
    subject: "business",
    image: "workspace.webp",
    description:
      "A fictional small-group session for exploring an idea before building it.",
  },
  {
    id: "notice-light",
    title: "A little more light",
    creator: "Casey Lane",
    courseId: "photography",
    location: "New York",
    month: "Oct",
    day: "03",
    date: "Saturday, 3 October 2026",
    time: "15:00 UTC",
    subject: "creative",
    image: "mountains.webp",
    description:
      "A sample creative session about noticing composition in everyday scenes.",
  },
  {
    id: "room-to-move",
    title: "Make room for movement",
    creator: "Alex Rowan",
    courseId: "strength",
    location: "Online",
    month: "Oct",
    day: "10",
    date: "Saturday, 10 October 2026",
    time: "10:00 UTC",
    subject: "fitness",
    image: "strength.webp",
    description:
      "A layout-study event linked to a fictional fitness course, not a prescribed exercise session.",
  },
  {
    id: "small-business",
    title: "Listen before you build",
    creator: "Nora Ellis",
    courseId: "research",
    location: "London",
    month: "Oct",
    day: "15",
    date: "Thursday, 15 October 2026",
    time: "17:00 UTC",
    subject: "business",
    image: "cafe.webp",
    description: "A fictional workshop exploring better customer questions.",
  },
  {
    id: "everyday-words",
    title: "Make your words clear",
    creator: "Robin Lee",
    courseId: "writing",
    location: "New York",
    month: "Nov",
    day: "06",
    date: "Friday, 6 November 2026",
    time: "16:00 UTC",
    subject: "creative",
    image: "notebook.webp",
    description:
      "An example small-group writing session. No instructor or venue is booked.",
  },
] as const;
export const patternLinks = [
  {
    href: "/preview/language",
    label: "Language selection & translated settings",
  },
  { href: "/preview/content", label: "Content preference / code-entry states" },
  { href: "/preview/events", label: "Event & location layouts" },
  { href: "/preview/channels", label: "Channel & schedule layouts" },
  { href: "/preview/recap", label: "Recap & milestone layouts" },
];
