import "server-only";
import { canReadDemoLesson } from "./catalog";
import type { Course, LessonBody } from "./types";
// Original demo lessons. Select bodies on the server; never serialize locked content.
const bodies: Record<string, LessonBody> = {
  "design-observe": { introduction: "Before you move a button or choose a color, look at what the page asks someone to do. Good observation gives a redesign a purpose.", sections: [
    { title: "Notice the first thing you see", body: "Open a screen you use often. Without interacting, write down the first three things that attract your attention. Compare that order with the task you came to accomplish. A mismatch is an observation to investigate, not an excuse to make everything larger." }, { title: "Separate the job from the decoration", body: "Describe the main action in one sentence: a person needs to find a lesson, compare an option, or continue unfinished work. Mark which elements support that action. Ask what information is missing before deciding what to remove." } ], exercise: "Choose one screen. Write its main job, the three strongest visual elements, and one question you would ask a person using it. Bring that question to the course discussion." },
  "design-hierarchy": { introduction: "Hierarchy is a deliberate order of attention. Give the essential information a clear place before adding more visual effects.", sections: [
    { title: "Group related information", body: "Put a title near its explanation and an action near the information needed to choose it. Use a larger gap between different groups than within one group. This makes relationships visible without another border around everything." }, { title: "Spend emphasis carefully", body: "Choose one primary action for the current task. Use type size, weight, space, and contrast as a small coordinated set. If every item is bold or brightly colored, compare two simpler alternatives before adding another treatment." } ], exercise: "Sketch the same screen with only text and spacing. Make its main action and two information groups clear without adding a card around each one." },
  "design-iterate": { introduction: "A small change is easier to understand when you know what it is supposed to improve. Keep a before state and test the same task afterward.", sections: [
    { title: "Name the expected improvement", body: "Write a specific hypothesis, such as: placing the lesson duration beside its title will make choosing a short lesson easier. Avoid judging the change only by whether it looks newer." }, { title: "Observe without coaching", body: "Ask someone to perform the task using the revised screen. Watch where they pause and what they expect an action to do. Preserve their words, compare the result with your hypothesis, and decide what to test next." } ], exercise: "Change one thing in your sketch. Record the task, your hypothesis, and what happened when someone tried it. Share the observation rather than a claim of success." },
  "web-purpose": { introduction: "A useful web page starts with a person trying to do something. The framework comes after that purpose, not before it.", sections: [
    { title: "Write the journey in plain words", body: "Describe the starting point, the decision, and the useful result. For a lesson library: I return, find my unfinished lesson, and continue reading. This sentence helps you decide which content and controls belong on the first screen." }, { title: "Include the less convenient states", body: "What happens when nothing is saved, a lesson is unavailable, or a request fails? Write a useful next step for each state. A complete small journey includes these cases rather than showing only its ideal screen." } ], exercise: "Choose one feature. Describe its successful journey and three states in which someone could get stuck. Write the next action for each state." },
  "writing-reader": { introduction: "Clear writing begins with a reader and a reason to read. A sentence that helps one person can be more useful than a paragraph that tries to impress everyone.", sections: [
    { title: "Choose the question you are answering", body: "Imagine one reader encountering the text for the first time. What are they trying to understand or decide? Write that question above your draft, then remove sentences that do not help answer it." }, { title: "Put the useful answer early", body: "Start with the information the reader needs. Add the reason, detail, or example after that. Keep the introduction only when it gives context the reader cannot otherwise infer." } ], exercise: "Take a paragraph from an email or page. Name its reader, write their question, and rewrite the opening to answer it directly." },
  "writing-edit": { introduction: "Specific details let readers judge an idea for themselves. Replace vague praise with an observable action, example, or limitation.", sections: [
    { title: "Underline claims", body: "Look for words such as easy, powerful, and innovative. Ask what the reader will actually be able to do. Replace the claim with a concrete explanation, without inventing numbers or promising an outcome you cannot support." }, { title: "Keep necessary qualifications", body: "Clarity does not mean removing every limitation. A short, direct qualification can prevent a misunderstanding. Put conditions close to the statement they affect." } ], exercise: "Rewrite three vague claims as specific descriptions. Mark any fact that you still need to verify rather than filling the gap with an assumption." },
  "writing-read": { introduction: "Your familiarity with a draft hides missing context. Give the words a test that does not rely on what you already know.", sections: [
    { title: "Read the draft aloud", body: "Notice where you need to restart a sentence or explain a term. Split a sentence when it is doing two different jobs. Keep the words the reader actually uses when they are accurate." }, { title: "Ask for a retelling", body: "Give the draft to someone without explaining it first. Ask what they think it means and what they would do next. Use the difference between your intention and their interpretation to guide the next edit." } ], exercise: "Ask someone to summarize your paragraph in one sentence. Compare it with your original goal, then make one targeted revision." },
  "photo-notice": { introduction: "Choosing a subject is also choosing what can stay outside the picture. Start with a small observation instead of a perfect location.", sections: [
    { title: "Name what caught your eye", body: "Choose a shape, a contrast, or a relationship between objects. Describe it in a few words before lifting the camera. This gives you a reason to choose one viewpoint over another." }, { title: "Try three deliberate variations", body: "Make one frame from where you are, one from closer, and one from a different angle. Keep the subject the same. Compare what each version includes and what it distracts from." } ], exercise: "Photograph one ordinary object from three viewpoints. Choose one image and explain what you left outside the frame. Respect other people's privacy while practicing." },
  "business-problem": { introduction: "An idea becomes easier to test when its intended customer and problem are specific. Start with what someone is trying to accomplish.", sections: [
    { title: "Describe the current workaround", body: "Ask how a person handles the problem today. Record the steps, inconvenience, and circumstances in their own words. Do not treat a polite response to your idea as evidence that someone will buy it." }, { title: "State what you do not know", body: "Separate observations from assumptions. A useful next test addresses an uncertainty that could change your decision. Choose a small way to learn without promising results or spending beyond your means." } ], exercise: "Write a problem statement with a person, a situation, and a current workaround. List three assumptions you would need to test before building a product." },
};
export function demoLessonBody(course: Course, lessonId: string): LessonBody | null {
  if (!canReadDemoLesson(course, lessonId)) return null;
  return bodies[lessonId] ?? null;
}
